services:
  web:
    image: nginx:alpine
    container_name: portfolio_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/remiguerin.fr
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - portfolio_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_php
    restart: unless-stopped
    working_dir: /var/www/remiguerin.fr
    volumes:
      - .:/var/www/remiguerin.fr
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge