version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_web
    restart: unless-stopped
    working_dir: /var/www/remiguerin.fr
    volumes:
      - .:/var/www/remiguerin.fr
      - ./nginx/default.conf:/etc/nginx/sites-available/default
    ports:
        - "80:80"
        - "443:443"
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    networks:
      - portfolio_network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: portfolio_php
    restart: unless-stopped
    working_dir: /var/www/remiguerin.fr
    volumes:
      - .:/var/www/remiguerin.fr
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge