name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs_on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build assets
      run: |
        npm install
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /app/portfolio
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php bin/console cache:clear --env=prod
          php bin/console doctrine:migrations:migrate --no-interaction
          sudo systemctl reload php8.2-fpm
          sudo systemctl reload nginx
